### ISSUE TITLE
Fail to import large CSV

### ISSUE THREAD

**Issue by fulldecent** [gristlabs/grist-core#901]
I am using Grist as recommended with [this omnibus setup](https://github.com/gristlabs/grist-omnibus?tab=readme-ov-file).

Importing a small CSV file was successful using this:

![Screenshot 2024-03-18 at 12 21 59](https://github.com/gristlabs/grist-core/assets/382183/e259a6b7-55b3-45d0-b7ce-23233d0bf270)

However, importing a large CSV file failed.

![Screenshot 2024-03-18 at 12 21 53](https://github.com/gristlabs/grist-core/assets/382183/6f38aabe-c458-40ab-ab6e-69d9343bfdd0)

The file I need to load is: 200MB, 30 columns, 400,000 rows.

---

# Work plan

- [ ] Update that error message to link to this issue and/or a relevant documentation page
- [ ] Document file size limits for import (if any) and any other exact, objective requirements on file input, link to these specifications from that error message and/or that documentation page
- [ ] Update that error message to link to log files or show other specific information why the file was not imported

**Comment by gabriel-v** [comment]
Wanted to say the same thing. Running docker container capped at 10G ram.

Here is a 2GB csv file download:

https://catalog.data.gov/dataset/crimes-2001-to-present/resource/31b027d7-b633-4e82-ad2e-cfa5caaf5837

https://data.cityofchicago.org/api/views/ijzp-q8t2/rows.csv?accessType=DOWNLOAD

---

Tried both with and without sandboxing. 

With sandbox, I get this on logs pretty quick:

```
2024-03-20 03:44:43.910 - warn: Sandbox unexpectedly exited with code 1 signal null sandboxPid=684, flavor=gvisor, command=undefined, entryPoint=(default), plugin=builtIn/core, docId=vdvs6jqzwmuzosEcHdoJoY
2024-03-20 03:44:43.927 - warn: Error during api call to /workspaces/2/import: Failed to parse CSV file.
Error: [Sandbox] PipeFromSandbox is closed:     raise Exception('gvisor runsc problem: ' + json.dumps(command))
```

I guess there's a low implicit memory limit for the sandbox?

---

With no sandbox, I get this:

![image](https://github.com/gristlabs/grist-core/assets/7493327/ea3c608b-27ac-4f80-9ca7-9872abe097ec)

```
2024-03-20 03:50:04.240 - warn: Sandbox unexpectedly exited with code null signal SIGKILL sandboxPid=23, flavor=unsandboxed, command=undefined, entryPoint=(default), plugin=builtIn/core, docId=vdvs6jqzwmuzosEcHdoJoY
```

and dmesg

```
[26021.168950] Memory cgroup out of memory: Killed process 137254 (python3.11) total-vm:10179908kB, anon-rss:10018296kB, file-rss:6912kB, shmem-rss:0kB, UID:0 pgtables:19992kB oom_score_adj:0
```

So it's using more than 10GB ram to parse the 2GB CSV file. Let's give it 20GB...

![Screenshot from 2024-03-20 06-02-13](https://github.com/gristlabs/grist-core/assets/7493327/32e7d763-5885-4fc4-9ee1-6dc1de11ccdb)

aaaand, boom

```
[26749.723969] Memory cgroup out of memory: Killed process 141164 (python3.11) total-vm:20545332kB, anon-rss:20259880kB, file-rss:7040kB, shmem-rss:0kB, UID:0 pgtables:40788kB oom_score_adj:0

```

![Screenshot from 2024-03-20 06-02-50](https://github.com/gristlabs/grist-core/assets/7493327/c9963801-2262-4116-b9cd-19b50848ea64)

Hey, it guessed the headers now...


---

Let's give it 40GB

![Screenshot from 2024-03-20 06-23-32](https://github.com/gristlabs/grist-core/assets/7493327/6338684c-dae3-4269-a07f-d767a604c094)

No more OOM, that's nice. Container process seems to be using at most 21GB, even through the container group itself peaks at 31GB.


Still, after a couple minutes the UI breaks down:

![Screenshot from 2024-03-20 06-08-55](https://github.com/gristlabs/grist-core/assets/7493327/92ee46cd-987a-47a0-96b6-2d571f5698db)


And there's no data in the `persist` folder.

---

Ok, let's cut down on the file size. After truncating first million rows (180MB):

![Screenshot from 2024-03-20 06-34-45](https://github.com/gristlabs/grist-core/assets/7493327/7efc0a79-a8e7-4699-a19b-92f5b9769bc8)

Ram usage tops out at 10G (50X increase from file size).


Seems to be fine so far - but then shows this screen with no data, clicking the "new table" button on the left starts this spinner.

![Screenshot from 2024-03-20 06-35-58](https://github.com/gristlabs/grist-core/assets/7493327/1e584b13-cfbc-4210-aab7-126ee311489f)


----

I can see from this two things:

- grist loads the CSV file completely into ram at upload time
- grist then processes it in memory at over 50X amplification

Both of these things can be fixed but it seems this was designed to fit everything into ram....

**Comment by ouvry-ems** [comment]
Thanks a lot @gabriel-v for those advanced tests!

I'm also having memory issues with importing only a 6MB Excel file and with this thread I understand that we're not alone having this exploding memory compared to the relatively small file size.

This is pretty irritating and limiting... Is there any update about this issue and improvements planned?

Cheers!
